/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Haochen' at '2/5/15 3:08 PM' with Gradle 2.2.1
 *
 * @author Haochen, @date 2/5/15 3:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
